### PR TITLE
Responsive Bugs

### LINKED ISSUE #37: When a panel hits 0% width, it doesn't recover again
To replicate:
If you resize the browser window so a % panel shrinks to 0%, then make the browser bigger again, the % panel remains at 0%.

Video:
https://github.com/user-attachments/assets/54d956d1-e04a-4510-8f08-87a5ee2cd722

Code sandbox:
https://codesandbox.io/p/devbox/agitated-shape-forked-crd4d2?file=%2Fapp%2Froutes%2F_index.tsx%3A13%2C6-13%2C16&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cm06wotv400063b6iggzje72a%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cm06wotv300033b6iu4f657f1%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cm06wotv300043b6iw3n0g4gc%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cm06wotv300053b6i59cp7up2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cm06wotv300033b6iu4f657f1%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cm06wotv300023b6ilrk6toez%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A10%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A10%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fremix.config.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cm06wpmb7002c3b6irvi5jpmv%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A20%252C%2522startColumn%2522%253A33%252C%2522endLineNumber%2522%253A20%252C%2522endColumn%2522%253A34%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cm06ydz3j00023b6jcj3ydo2s%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A13%252C%2522startColumn%2522%253A6%252C%2522endLineNumber%2522%253A13%252C%2522endColumn%2522%253A16%257D%255D%252C%2522filepath%2522%253A%2522%252Fapp%252Froutes%252F_index.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522id%2522%253A%2522cm06wotv300033b6iu4f657f1%2522%252C%2522activeTabId%2522%253A%2522cm06ydz3j00023b6jcj3ydo2s%2522%257D%252C%2522cm06wotv300053b6i59cp7up2%2522%253A%257B%2522id%2522%253A%2522cm06wotv300053b6i59cp7up2%2522%252C%2522activeTabId%2522%253A%2522cm06wv729003u3b6jx55v03x3%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A3000%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522cm06wv729003u3b6jx55v03x3%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522cm06wotv300043b6iw3n0g4gc%2522%253A%257B%2522id%2522%253A%2522cm06wotv300043b6iw3n0g4gc%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522cm06wpgz6001w3b6irh98rygr%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cm06wpgz6001w3b6irh98rygr%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### PR DESCRIPTION
**Pull request by hipstersmoothie**
closes #37

### CODE REVIEW

File: packages/state/src/index.ts [hunk 1]
```diff
@@ -1760,21 +1811,11 @@ export const groupMachine = createMachine(
...
-          for (const [id, size] of Object.entries(event.childrenSizes)) {
-            const item = context.items.find((i) => i.id === id);
-
-            if (!isPanelData(item)) {
-              continue;
-            }
-
-            item.currentValue = makePixelUnit(
-              orientation === "horizontal" ? size.width : size.height
-            );
```
Comment (hipstersmoothie) [inline packages/state/src/index.ts:1774]: The first big change in this PR is that when we get the actual size of the panel we don't immediately set its size to that. We only use the actual size during resizing operations.

If we update immediately the percentages get updates as the container resizes. Which leads to a bunch of undesired behaviors:

- When a panel renders at 0 initially, it can never recover
- when a panel is resized to 0 it can never recover
- if you resize it updates the percentages and your panels end up in different places

So instead we don't updates the percentages at all and instead just track what size it was last rendered at.

File: packages/state/src/index.ts [hunk 2]
```diff
@@ -947,6 +958,16 @@ export function prepareItems(context: GroupMachineContextValue): Item[] {
...
 
+    if (item.lastKnownSize) {
+      const lastSize = makePixelUnit(
+        context.orientation === "horizontal"
+          ? item.lastKnownSize.width
+          : item.lastKnownSize.height
+      );
+      newItems.push({ ...item, currentValue: lastSize });
+      continue;
+    }
```
Comment (hipstersmoothie) [inline packages/state/src/index.ts:969]: When we prepare for updating the layout we use the last updated size if it exists.

File: packages/state/src/index.ts [hunk 3]
```diff
@@ -825,6 +827,15 @@ export function buildTemplate(context: GroupMachineContextValue) {
...
         } else if (item.currentValue.type === "percent") {
+          if (
+            !hasSeenFillPanel &&
+            (item.max === "1fr" ||
+              (item.max.type === "percent" && item.max.value.eq(100)))
+          ) {
+            hasSeenFillPanel = true;
+            return `minmax(${min}, 1fr)`;
+          }
+
```
Comment (hipstersmoothie) [inline packages/state/src/index.ts:838]: The second big change in this PR is the concept of a "fill" panel. 

During coding this PR I found a problem:

1. render at a small screen size with 1 panels that is min:200px max: 400px
2. resize to much bigger
3. The two panels both get ~50%, at bigger sizes one panel is capped at 400px and the group doesn't fill the space

The "fill" panel fixes this. I found that if we just assign 1 panel to `1fr` and all siblings are pixels/percentages it lays out correctly. When the container grows this fill panel grows to fit the space. 

This is really needed cause we don't update any layout on resize and leave that all to `grid`.

Comment (hipstersmoothie) [reply packages/state/src/index.ts:838]: In the future we could make the fill panel configurable

**Comment by hipstersmoothie** [comment]
:rocket: PR was released in [`v0.4.1`](https://github.com/hipstersmoothie/react-window-splitter/releases/tag/v0.4.1) :rocket:
